name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Python
        run: python main.py

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy fake
        run: echo "Deploy realizado"
